USE ApplicationDB;

INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('Ron Jon UV Protection Rainbow Bucket Hat', 'accessory', 'hat', 24.00, 5.0, '1881012900001010', 'https://www.ronjonsurfshop.com/assets/ea/69/ea69a4a5-dd8c-4cf9-aea1-5d64d25fb1c3/d494x494-18810129000-ron-jon-rainbow-bucket-hat-front.jpg', 'Ron Jon Surf Shop', 14.50, 22.40, 22.40, 0.08, 'Show your love for the beach with colors as gorgeous as the beach at dusk.');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('Outdoor Summer Boonie Hat for any Outdoor Activity', 'accessory', 'hat', 14.99, 3.7, '1132004000090230', 'https://i5.walmartimages.com/asr/7131e4aa-21b5-4a46-9edd-3b67c135a02d_1.a4668bb2484065b442d57eb5f04508be.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF', 'manufacturer', 13.17, 24.72, 24.72, 0.10, 'OUTDOOR BOONIE HAT : Introducing a super stylish boonie hat for all ages resembling a sleek military style cap. Each hat features an adjustable string / chin strap to provide additional security and comfort even in high level motion activity. The floppy look gives a sporty and rugged look for you to take on the great outdoors in style!');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('NEW HERBIE! HUSKER BASEBALL HERBIE HERO CAP', 'accessory', 'hat', 29.99, 0.0, 'HT-G7152', 'https://www.bestofbigred.com/resize/Shared/Images/Product/NEW-HERBIE-Husker-Baseball-Herbie-Hero-Cap/HT-G7152.jpg?bw=1000&w=1000&bh=1000&h=1000', 'manufacturer', 13.48, 20.44, 16.58, 00.15, 'Scarlet EZA adjustable snapback hat. Features Herbie Husker with a baseball bat. 100% cotton twill. By Legacy. OSFA');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('New York Yankees New Era 2023 Spring Training Fitted Hat', 'accessory', 'hat', 29.99, 4.2, '4991352', 'https://fanatics.frgimages.com/new-york-yankees/mens-new-era-navy-new-york-yankees-2023-spring-training-59fifty-fitted-hat_ss5_p-4991352+pv-1+u-oajxizgg1fbrgzw7afsx+v-umk2jzisxtosb9xi2pon.jpg?_hv=2&w=900', 'manufacturer', 15.50, 21.00, 14.50, 00.12, 'Represent your favorite team with the same style the players wear. This New York Yankees 2023 Spring Training 59FIFTY Fitted Hat from New Era will make you feel like you''re taking the field with your favorite MLB stars every time you put it on. The sleek New York Yankees graphics are sure to help you stand out in any ballpark you step in this season.');

INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('Timex Ironman Classic 30 Full-Size 38mm Watch', 'accessory', 'watch', 32.73, 4.6, 'B0842QF6JD', 'https://m.media-amazon.com/images/I/81YDWDSYSeL._AC_UY500_.jpg', 'Timex', 8.79, 7.50, 6.40, 0.08, 'Adjustable black 18mm resin strap fits up to 8-inch wrist circumference. 100-hour chronograph with 30-lap memory; 24-hour countdown timer. 3 daily, weekday or weekend alarms; 24-hour military time mode; 2 time zones; day, date & month calendar. Gray & black 38mm resin case with acrylic lens; gray digital display; Indiglo light-up watch dial. Water resistant to 100m (330ft): in general, suitable for swimming and snorkeling, but not diving');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('GRV Smart Watch for iOS and Android Phones', 'accessory', 'watch', 24.59, 4.1, 'B09J8SKX9G', 'https://m.media-amazon.com/images/I/51jzaIqrKNL._AC_SX569_.jpg', 'GRV', 25.00, 3.50, 1.70, 0.03, 'Accurate Fitness Tracker with 9 Sport Modes. This fitness tracker watch can accurately track calories burned, steps taken, sleep quality. 9 sports modes are optional, including various outdoor and indoor activities, allow you to get the real-time stats during your workouts on the watch. You can also connect it to smartphone''s GPS to track all your workout routes and distance traveled during exercise.');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('Amazfit Band 5 Activity Fitness Tracker with Alexa Built-in', 'accessory', 'watch', 31.99, 4.1, 'S2005OV1N', 'https://m.media-amazon.com/images/I/51ja6ds+pML._AC_SX679_.jpg', 'Amazfit', 1.27, 1.91, 4.72, 0.02, 'AMAZON ALEXA BUILT-IN: Talk to Amazon Alexa on your Amazfit Band 5. Ask questions, get translations, set alarms, and timers, create shopping lists, check the weather, control your smart home devices, and more.');
INSERT INTO Product (name, broadType, clothingType, price, numStars, sku, image, manufacturer, height, length, width, weight, description) VALUES ('Casio F91W-1 Classic Resin Strap Digital Sport Watch', 'accessory', 'watch', 15.84, 4.6, 'B000GAWSDG', 'https://m.media-amazon.com/images/I/51Nk5SEBARL._AC_SY879_.jpg', 'Casio', 9.00, 34.00, 39.00, 0.05, 'LED light, Stopwatch, Daily Alarm. Auto-calendar, 12/24 Hour Format. Approx. battery life: 7 years on CR2016. Water Resistant - Do not submerge in water, item is not waterproof, not meant for showering/bathing or swimming');
